from django.urls import path
from si_mbe import views


urlpatterns = [
     path('', views.Home.as_view(), name='homepage'),
     path('sparepart/find/', views.SearchSparepart.as_view(), name='search_sparepart'),

     # Admin endpoint access
     path('admin/', views.AdminDashboard.as_view(), name='admin_dashboard'),
     path('admin/sparepart/', views.SparepartDataList.as_view(), name='sparepart_data_list'),
     path('admin/sparepart/add/', views.SparepartDataAdd.as_view(), name='sparepart_data_add'),
     path('admin/sparepart/edit/<int:sparepart_id>/', views.SparepartDataUpdate.as_view(),
          name='sparepart_data_update'),
     path('admin/sparepart/delete/<int:sparepart_id>/', views.SparepartDataDelete.as_view(),
          name='sparepart_data_delete'),
     path('admin/sales/', views.SalesList.as_view(), name='sales_list'),
     path('admin/sales/add/', views.SalesAdd.as_view(), name='sales_add'),
     path('admin/sales/edit/<int:sales_id>/', views.SalesUpdate.as_view(), name='sales_update'),
     path('admin/sales/delete/<int:sales_id>/', views.SalesDelete.as_view(), name='sales_delete'),
     path('admin/restock/', views.RestockList.as_view(), name='restock_list'),
     path('admin/restock/add/', views.RestockAdd.as_view(), name='restock_add'),
     path('admin/restock/edit/<int:restock_id>/', views.RestockUpdate.as_view(), name='restock_update'),
     path('admin/restock/delete/<int:restock_id>/', views.RestockDelete.as_view(), name='restock_delete'),
     path('admin/supplier/', views.SupplierList.as_view(), name='supplier_list'),
     path('admin/supplier/add/', views.SupplierAdd.as_view(), name='supplier_add'),
     path('admin/supplier/edit/<int:supplier_id>/', views.SupplierUpdate.as_view(), name='supplier_update'),
     path('admin/supplier/delete/<int:supplier_id>/', views.SupplierDelete.as_view(), name='supplier_delete'),
     path('admin/service/', views.ServiceList.as_view(), name='service_list'),
     path('admin/service/add/', views.ServiceAdd.as_view(), name='service_add'),
     path('admin/service/edit/<int:service_id>/', views.ServiceUpdate.as_view(), name='service_update'),
     path('admin/service/delete/<int:service_id>/', views.ServiceDelete.as_view(), name='service_delete'),
     path('admin/brand/', views.BrandList.as_view(), name='brand_list'),
     path('admin/brand/add/', views.BrandAdd.as_view(), name='brand_add'),
     path('admin/brand/edit/<int:brand_id>/', views.BrandUpdate.as_view(), name='brand_update'),
     path('admin/brand/delete/<int:brand_id>/', views.BrandDelete.as_view(), name='brand_delete'),
     path('admin/category/', views.CategoryList.as_view(), name='category_list'),
     path('admin/category/add/', views.CategoryAdd.as_view(), name='category_add'),
     path('admin/category/edit/<int:category_id>/', views.CategoryUpdate.as_view(), name='category_update'),
     path('admin/category/delete/<int:category_id>/', views.CategoryDelete.as_view(), name='category_delete'),
     path('admin/customer/', views.CustomerList.as_view(), name='customer_list'),
     path('admin/customer/add/', views.CustomerAdd.as_view(), name='customer_add'),
     path('admin/customer/edit/<int:customer_id>/', views.CustomerUpdate.as_view(), name='customer_update'),
     path('admin/customer/delete/<int:customer_id>/', views.CustomerDelete.as_view(), name='customer_delete'),
     path('admin/mechanic/', views.MechanicList.as_view(), name='mechanic_list'),
     path('admin/mechanic/add/', views.MechanicAdd.as_view(), name='mechanic_add'),
     path('admin/mechanic/edit/<int:mechanic_id>/', views.MechanicUpdate.as_view(), name='mechanic_update'),
     path('admin/mechanic/delete/<int:mechanic_id>/', views.MechanicDelete.as_view(), name='mechanic_delete'),
     path('admin/salesman/', views.SalesmanList.as_view(), name='salesman_list'),
     path('admin/salesman/add/', views.SalesmanAdd.as_view(), name='salesman_add'),
     path('admin/salesman/edit/<int:salesman_id>/', views.SalesmanUpdate.as_view(), name='salesman_update'),
     path('admin/salesman/delete/<int:salesman_id>/', views.SalesmanDelete.as_view(), name='salesman_delete'),

     # Owner endpoint access
     path('owner/', views.OwnerDashboard.as_view(), name='owner_dashboard'),
     path('owner/report/sales/', views.SalesReport.as_view(), name='sales_report'),
     path('owner/report/restock/', views.RestockReport.as_view(), name='restock_report'),
     path('owner/report/service/', views.ServiceReport.as_view(), name='service_report'),
     path('owner/profile/<int:user_id>/', views.ProfileDetail.as_view(), name='profile_detail'),
     path('owner/profile/edit/<int:user_id>/', views.ProfileUpdate.as_view(), name='profile_update'),
     path('owner/log/', views.LogList.as_view(), name='log'),
     path('owner/admin/', views.AdminList.as_view(), name='admin_list'),
     path('owner/admin/add/', views.AdminAdd.as_view(), name='admin_add'),
     path('owner/admin/edit/<int:pk>/', views.AdminUpdate.as_view(), name='admin_update'),
     path('owner/admin/delete/<int:pk>/', views.AdminDelete.as_view(), name='admin_delete'),
]
