# Generated by Django 4.1.3 on 2022-12-02 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('si_mbe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparepart',
            old_name='type',
            new_name='sparepart_type',
        ),
        migrations.RemoveField(
            model_name='log',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='restock',
            name='total',
        ),
        migrations.RemoveField(
            model_name='restock_detail',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='total',
        ),
        migrations.RemoveField(
            model_name='sales_detail',
            name='individual_price',
        ),
        migrations.RemoveField(
            model_name='sales_detail',
            name='total_price',
        ),
        migrations.AddField(
            model_name='extend_user',
            name='contact_number',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='extend_user',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='restock',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='restock',
            name='no_faktur',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='sales_detail',
            name='is_grosir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='grosir_price',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='motor_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='partnumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='salesman_contact',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='supplier',
            name='salesman_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restock',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='sales',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
