# Generated by Django 4.1.3 on 2022-12-12 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0002_rename_type_sparepart_sparepart_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock_detail',
            name='restock_id',
            field=models.ForeignKey(db_column='restock_id', on_delete=django.db.models.deletion.CASCADE, to='si_mbe.restock'),
        ),
    ]
