# Generated by Django 4.1.3 on 2022-12-16 15:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('si_mbe', '0003_alter_restock_detail_restock_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extend_user',
            new_name='Profile',
        ),
    ]
