# Generated by Django 4.1.3 on 2022-12-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0004_rename_extend_user_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
