# Generated by Django 4.1.3 on 2022-12-23 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('si_mbe', '0007_rename_log_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
                ('number_of_service', models.PositiveSmallIntegerField()),
                ('total_payment', models.DecimalField(decimal_places=0, max_digits=15)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('mechanic_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'mechanic',
            },
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('salesman_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'salesman',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('is_paid_off', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('police_number', models.CharField(max_length=10)),
                ('motor_type', models.CharField(max_length=20)),
                ('deposit', models.DecimalField(decimal_places=0, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('customer_id', models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='si_mbe.customer')),
                ('mechanic_id', models.ForeignKey(db_column='mechanic_id', on_delete=django.db.models.deletion.PROTECT, to='si_mbe.mechanic')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Service_action',
            fields=[
                ('service_action_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('cost', models.DecimalField(decimal_places=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_id', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.PROTECT, to='si_mbe.service')),
            ],
            options={
                'db_table': 'service_action',
            },
        ),
        migrations.CreateModel(
            name='Service_sparepart',
            fields=[
                ('service_sparepart_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_id', models.ForeignKey(db_column='service_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='si_mbe.service')),
            ],
            options={
                'db_table': 'service_sparepart',
            },
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='contact_number',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='sales_detail',
            old_name='is_grosir',
            new_name='is_workshop',
        ),
        migrations.RenameField(
            model_name='sparepart',
            old_name='grosir_price',
            new_name='install_price',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='contact_number',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='table_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='customer_contact',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='salesman_contact',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='salesman_name',
        ),
        migrations.AddField(
            model_name='logs',
            name='table',
            field=models.CharField(default='Sparepart', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('P', 'Pemilik'), ('A', 'Admin')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='restock',
            name='deposit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='restock_detail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='deposit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='sales_detail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sparepart',
            name='image',
            field=models.ImageField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='workshop_price',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='sparepart_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='storage',
            name='location',
            field=models.CharField(choices=[('1', 'Bengkel 1 Jalan ...'), ('2', 'Bengkel 2 Jalan ...')], default='1', max_length=30),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='service_sparepart',
            name='sparepart_id',
            field=models.ForeignKey(db_column='sparepart_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='si_mbe.sparepart'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='supplier_id',
            field=models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, to='si_mbe.supplier'),
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='si_mbe.customer'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='category_id',
            field=models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='si_mbe.category'),
        ),
        migrations.AddConstraint(
            model_name='service_sparepart',
            constraint=models.UniqueConstraint(fields=('service_id', 'sparepart_id'), name='unique_service_sparepart'),
        ),
    ]
