# Generated by Django 4.1.3 on 2022-12-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0008_category_customer_mechanic_salesman_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='deposit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
