# Generated by Django 4.1.3 on 2022-12-24 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0009_alter_service_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='restock',
            name='salesman_id',
            field=models.ForeignKey(db_column='salesman_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='si_mbe.salesman'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
