# Generated by Django 4.1.3 on 2022-12-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0010_restock_salesman_id_alter_storage_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number_of_service',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_payment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
