# Generated by Django 4.1.3 on 2022-12-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0011_alter_customer_number_of_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
    ]
