# Generated by Django 4.1.3 on 2022-12-27 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0012_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='si_mbe.customer'),
        ),
        migrations.AlterField(
            model_name='service',
            name='mechanic_id',
            field=models.ForeignKey(db_column='mechanic_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='si_mbe.mechanic'),
        ),
        migrations.AlterField(
            model_name='service_action',
            name='service_id',
            field=models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='si_mbe.service'),
        ),
        migrations.AlterField(
            model_name='service_sparepart',
            name='service_id',
            field=models.ForeignKey(db_column='service_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='si_mbe.service'),
        ),
        migrations.AlterField(
            model_name='service_sparepart',
            name='sparepart_id',
            field=models.ForeignKey(db_column='sparepart_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='si_mbe.sparepart'),
        ),
    ]
