# Generated by Django 4.1.3 on 2022-12-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0013_alter_service_customer_id_alter_service_mechanic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
