# Generated by Django 4.1.3 on 2022-12-30 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0014_alter_mechanic_address_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock_detail',
            name='restock_id',
            field=models.ForeignKey(db_column='restock_id', on_delete=django.db.models.deletion.CASCADE, related_name='restock_details', to='si_mbe.restock'),
        ),
    ]
