# Generated by Django 4.1.3 on 2022-12-30 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0015_alter_restock_detail_restock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock_detail',
            name='restock_id',
            field=models.ForeignKey(db_column='restock_id', on_delete=django.db.models.deletion.CASCADE, to='si_mbe.restock'),
        ),
    ]
