# Generated by Django 4.1.3 on 2022-12-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0017_sparepart_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='quantity',
            field=models.SmallIntegerField(),
        ),
    ]
