# Generated by Django 4.1.3 on 2023-01-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0019_alter_sparepart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.AddField(
            model_name='supplier',
            name='rekening_bank',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rekening_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rekening_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
