# Generated by Django 4.1.3 on 2023-01-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0020_remove_supplier_address_supplier_rekening_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='rekening_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
