# Generated by Django 4.1.3 on 2023-01-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0021_alter_supplier_rekening_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='responsibility',
            field=models.CharField(default='', max_length=20),
        ),
    ]
