# Generated by Django 4.1.3 on 2023-01-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0022_salesman_responsibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='number_of_service',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='total_payment',
        ),
    ]
