# Generated by Django 4.1.3 on 2023-01-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0023_remove_customer_number_of_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restock',
            name='supplier_id',
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='quantity',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
