# Generated by Django 4.1.3 on 2023-01-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0024_remove_restock_supplier_id_alter_sparepart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='storage_id',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='storage_code',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='install_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='workshop_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15),
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
