# Generated by Django 4.1.3 on 2023-01-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0025_remove_sparepart_storage_id_sparepart_storage_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_detail',
            name='is_workshop',
        ),
        migrations.AddField(
            model_name='sales',
            name='is_workshop',
            field=models.BooleanField(default=False),
        ),
    ]
