# Generated by Django 4.1.3 on 2023-01-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0026_remove_sales_detail_is_workshop_sales_is_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
