# Generated by Django 4.1.3 on 2023-01-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0027_alter_service_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='motor_type',
            field=models.TextField(default=''),
        ),
    ]
