# Generated by Django 4.1.3 on 2023-01-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0028_alter_sparepart_motor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='image',
        ),
    ]
