# Generated by Django 4.1.3 on 2023-01-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0029_remove_sparepart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='is_workshop',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_workshop',
            field=models.BooleanField(default=False),
        ),
    ]
