# Generated by Django 4.1.3 on 2023-01-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_mbe', '0030_remove_sales_is_workshop_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
